export const PRIMARY_BUTTON_MIN_HEIGHT = 52;

export const PRIMARY_BUTTON_CONTENT_MIN_HEIGHT = 24;

export const PRIMARY_BUTTON_ENABLE_TRANSITION_MS = 220;

export const PRIMARY_BUTTON_PRESS_COLOR_IN_MS = 100;

export const PRIMARY_BUTTON_PRESS_COLOR_OUT_MS = 180;
